### ISSUE TITLE
Add summary statistics command

### ISSUE THREAD

**Issue by yashma-sonara** [AY2324S2-CS2103T-T09-1/tp#109]

**Comment by willowisp01** [comment]
What do you want to name this command? I'll also be adding a feature to show how the _group_ is doing, which I thought I would name `stats`. Let me know if there is any conflict in the naming. Thanks!

**Comment by yashma-sonara** [comment]
for now, I have the command as "summary"
As of now, I am able to output the mean of all grades and # of students, but  I am trying to output a popup with the fx chart.
