### ISSUE TITLE
[PE-D][Tester C] SetWeak Command does not affect the archived person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-1/tp#182]
Description: As a user, I would believe that an archived person would have their weak tag removed when the weak threshold changes.

Suggestion: Apply the changes in the weak threshold to that of the archived student lists as well.

Steps to Reproduce:
1. create 2 users both of grade C
2. setweak command to C
3. archive 1 user 
4. setweak command to D
5. weak tag is not removed from the archived user

Evidence:
![Screenshot 2024-04-05 at 5.36.27 PM.png](https://raw.githubusercontent.com/jaejayrome/ped/main/files/6db633a7-9b46-48b3-a1f8-53381d82bd50.png)

Additional Notes: NIL

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jaejayrome/ped#9

**Comment by willowisp01** [comment]
Won't fix. Archive serves to store information from some previous point in time. When archiving a student, their status as "weak" is also archived. Hence they are historically "weak" even if the current marker changes.
