### ISSUE TITLE
[PE-D][Tester D] Changing the data to include null in addressbook causes the app to crash.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-1/tp#193]
![image.png](https://raw.githubusercontent.com/ryanlimdx/ped/main/files/a63fcc2c-3647-40b6-8dc2-508737f4327c.png)

Editing the data file as mentioned in the UG, a user input of null will cause the app to crash instead of booting up on a clean state.

![image.png](https://raw.githubusercontent.com/ryanlimdx/ped/main/files/a4668b2a-fbeb-49ac-a95a-88e4dd419185.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ryanlimdx/ped#16

**Comment by willowisp01** [comment]
Won't fix. The caution message states that certain edits can cause TeachStack to behave unexpectedly.
