### ISSUE TITLE
[PE-D][Tester E] No support for chinese

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-1/tp#194]
![image.png](https://raw.githubusercontent.com/tanguoyang/ped/main/files/b103ff0a-89d3-4576-b66c-68729feabb10.png)

The address book does not support chinese names. Would be good to specify locality and language restrictions in your user guide!

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tanguoyang/ped#3

**Comment by JiaXinEu** [comment]
Requires a feature change
