### ISSUE TITLE
Update AboutUs page

### ISSUE THREAD

**Issue by JiaXinEu** [AY2324S2-CS2103T-T09-1/tp#2]
- Add your own details. Include a suitable photo.

 - The filename of the profile photo should be docs/images/github_username_in_lower_case.png

- Note the need for lower case ( why lowercase?) e.g. JohnDoe123 -> docs/images/johndoe123.png not docs/images/JohnDoe123.png.

- If your photo is in jpg format, name the file as .png anyway.

- Indicate the different roles played and responsibilities held by each team member.

**Comment by willowisp01** [comment]
good teamwork!
